config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :routers

end

app/models/router.rb
class Router < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/routers_controller.rb
class RoutersController < ApplicationController
  before_action :set_router, only: [:show, :edit, :update, :destroy]

  # GET /routers
  # GET /routers.json
  def index
    @routers = Router.all
  end

  # GET /routers/1
  # GET /routers/1.json
  def show
  end

  # GET /routers/new
  def new
    @router = Router.new
  end

  # GET /routers/1/edit
  def edit
  end

  # POST /routers
  # POST /routers.json
  def create
    @router = Router.new(router_params)

    respond_to do |format|
      if @router.save
        format.html { redirect_to @router, notice: 'Router was successfully created.' }
        format.json { render action: 'show', status: :created, location: @router }
      else
        format.html { render action: 'new' }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routers/1
  # PATCH/PUT /routers/1.json
  def update
    respond_to do |format|
      if @router.update(router_params)
        format.html { redirect_to @router, notice: 'Router was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @router }
      else
        format.html { render action: 'edit' }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routers/1
  # DELETE /routers/1.json
  def destroy
    @router.destroy
    respond_to do |format|
      format.html { redirect_to routers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_router
      @router = Router.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def router_params
      params.require(:router).permit(:about, :about_lnk, :connection, :connection_lnk)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raskroy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/routers/_form.html.erb
<%= form_for(@router) do |f| %>
  <% if @router.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@router.errors.count, "error") %> prohibited this router from being saved:</h2>

      <ul>
      <% @router.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :about_lnk %><br>
    <%= f.text_field :about_lnk %>
  </div>
  <div class="field">
    <%= f.label :connection %><br>
    <%= f.text_area :connection %>
  </div>
  <div class="field">
    <%= f.label :connection_lnk %><br>
    <%= f.text_field :connection_lnk %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routers/edit.html.erb
<h1>Editing Router</h1>

<%= render 'form' %>

<%= link_to 'Show', @router %> |
<%= link_to 'Back', routers_path %>

app/views/routers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Routers</h1>

<table>
  <thead>
    <tr>
      <th>About</th>
      <th>About lnk</th>
      <th>Connection</th>
      <th>Connection lnk</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routers.each do |router| %>
      <tr>
        <td><%= router.about %></td>
        <td><%= router.about_lnk %></td>
        <td><%= router.connection %></td>
        <td><%= router.connection_lnk %></td>
        <td><%= link_to 'Show', router %></td>
        <td><%= link_to 'Edit', edit_router_path(router) %></td>
        <td><%= link_to 'Destroy', router, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Router', new_router_path %>

app/views/routers/new.html.erb
<h1>New Router</h1>

<%= render 'form' %>

<%= link_to 'Back', routers_path %>

app/views/routers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>About:</strong>
  <%= @router.about %>
</p>

<p>
  <strong>About lnk:</strong>
  <%= @router.about_lnk %>
</p>

<p>
  <strong>Connection:</strong>
  <%= @router.connection %>
</p>

<p>
  <strong>Connection lnk:</strong>
  <%= @router.connection_lnk %>
</p>

<%= link_to 'Edit', edit_router_path(@router) %> |
<%= link_to 'Back', routers_path %>